# Generated by Django 5.2.4 on 2025-08-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('veiculo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('quantidade_inicial', models.IntegerField()),
                ('quantidade_final', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='galeria.peca')),
            ],
        ),
    ]
