# Generated by Django 5.2.4 on 2025-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
