# Generated by Django 5.2.4 on 2025-09-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_detalhespeca_quantidade_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhespeca',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='galeria.peca'),
        ),
    ]
